embedding_size: 64
n_ui_layers: 2
n_layers: 1

learning_rate_scheduler: [0.96, 50]
reg_weight: 1e-04

knn_k: 10 # [10, 50, 100]

learning_rate: 0.001

cl_ip_loss: [0.01] # [0.1, 0.01, 0.001]

uicl_loss: [0.01] # [0.1, 0.01, 0.001]

kl_loss: [0.01] # [0.1, 0.01, 0.001]

drop: 0.1

res_conn: [0.1, 0.5, 0.9] # [0.1, 0.9] #

hyper_parameters: ["cl_ip_loss", "uicl_loss", "res_conn", "kl_loss"]